# Габриэле Галлони

> Молодой поэт Габриэле Галлони (Gabriele Galloni) ушел из жизни в возрасте 25 лет. Он был провозглашен в Интернете одним из «лучших поэтов своего поколения», несколько писателей и коллег, близко его знавших, помнят его замкнутый образ жизни, его тягу к теме смерти и «хроникам конца».
>
> (1995-2020)

### **Бестиарий праздничных дней**

**Кошка**

«Не будет у тебя другого Бога, кроме меня»,\
мяукает кошка. Она рыжая, с белыми крапинками -\
очень сильно дрожит, не зная почему.

**Гусь**

Гусь теперь знает, когда придет смерть -\
в целом он это принимает неплохо.\
Одну за другой, она закрывает за ним\
все двери.

**Коза**

Коза играет со святым Себастьяном -\
зализывает его раны и утешает его.\
Ласкает всю его руку.

**Слон**

У слона, знаете ли, есть культ предков -\
все они будут с ним всегда;\
но во сне он о них понятия не имеет.

**Хамелеон**

Всегда похож на того, кем не является.\
Иногда на дерево, иногда на другого зверя -\
случается, что ночью ты похожа на меня.

### **Из книги “В каком свете они падают”**

Я знал человека, который гадал\
по руке мертвым. Он предпочитал тех\
кому меньше двадцати лет:\
каждое воскресенье в морге\
он предсказывал им\
координаты другой жизни.\
\
\*\*\*\
\
У мертвецов носы становятся тоньше. Когда\
мертвецы тебе снятся, носы они прикрывают.\
Увидеть, как они проходят мимо с закрытыми лицами\
из коридора в ванную или на кухню - это нормально.\
\
\*\*\*\
\
Мертвые пытаются нас утешить,\
но их попытки непонятны:\
это промахи, спотыкания, невнятные\
разговоры. Они знают, как одной рукой любить Нас,\
а другой – Невидимое.\*\*\
\
\*\*\*\
\
Мертвые пишут\
бесконечные любовные письма.\
Они посылают их ранним утром.\
