## Эуджинио Монтале {style="gray"}

> Эуджинио Монтале (Eugenio Montale) - Нобелевский лауреат по литературе 1975 года, по праву считается одним из основателей герметизма - направления в итальянской поэзии, базирующегося на абстрагировании от «непоэтической» реальности. Приведенные ниже стихотворения были опубликованы в сборнике “Quaderno di Quatro Anni 91974-1977)”, Mondadori, Milano. Стихотворение ‘Аспазия’ названо по имени греческой гетеры пятого века до нашей эры, подруги Перикла, необыкновенной красавицы, державшей салон, который посещали такие выдающиеся люди как Сократ, Платон, Еврипид, Геродот и другие замечательные жители Афин того времени. Правда героиня стихотворения несколько отличается от своей предшественницы.
>
> (1896 - 1981)

**Аспазия**

Поздним вечером мужики\
забирались к ней в комнату\
через окно, благо жила на первом этаже.\
Я прозвал её Аспазия и ей это нравилось.\
Потом она от нас уехала, работала в баре,\
парикмахерской и где-то ещё.\
Изредка я её встречал\
и тогда громко орал: Аспазия!\
а она на ходу мне улыбалась.\
Были бы мы с ней ровесники, да она давно умерла.\
Когда попаду в ад, то по старой привычке\
крикну: Аспазия! первой же улыбающейся тени,\
a та, естественно, пройдет мимо.\
Так мы и не узнаем, кем же она была,\
та бабочка, легко откликавшаяся на имя, которое\
я ей выбрал.\
<br/>

**Поэт**

**\
**Немного жить мне осталось, но надеюсь\
найти повод посвятить следующему тирану\
мои скромные вирши. И не прикажет он\
чтоб я перерезал себе вены, как Нерон повелел Лукану.\
Он захочет, чтобы восхищение шло от чистого сердца,\
и получит его в избытке. К тому же\
смогу оставить незабываемый след.\
Ведь в поэзии ценится не содержание,\
а Форма.\
