# Антонио Наззаро

> Антонио Наззаро (Antonio Nazzaro) - журналист, поэт, переводчик, видеохудожник , культурный атташе Италии в Венесуэле. Он является главным редактором нескольких сборников итальянской и латиноамериканской поэзии для разных издательств. Он опубликовал антологии: Migrant Love and the Last Cigarette (RiL Editores, Чили; Arcoiris, Италия, 2018), Corpi Fumanti (Uniediciones, Богота, 2019) и Diario amoroso senza date, Fotoromanzo poetico (Edizioni Carpa Koi, Италия, 2021). ), Диктатура любви (Edizioni Delta 3, коллекция Aelanum, Италия, 2022). Книга рассказов: Odore a… (Edizioni Arcoiris, Италия, 2014) и книга новостей и поэзии: Записки из Венесуэлы, 2017, Жизнь в протестах (Edizioni Arcoiris, Италия, 2017). Его тексты публиковались на разных языках в национальных и международных журналах и антологиях.
>
> (род. 1963)

\
Легко узнать эмигранта:\
даже под полуденным солнцем\
он отбрасывает\
две тени.\
\
\*\*\*

За несколько сольди\
сдам в аренду сердце,\
глаза подарю,\
руки не продаются -\
к красоте\
можно только прикaсaться.\
Hе знаю люблю ли я тебя,\
но дом и имя у меня появляются\
только, когда ты мне звонишь.\

\*\*\*\
\
Поцелуи\
Ласкаю тебя, словно выдох ветра, что приподымает платья.\
Улыбками целуют незаметно.\
Плывут к горизонту любви поцелуи из стихов, написанных на бумажных\
корабликах.\
Поцелуй из тех, что ночами бегают по тротуарам и сидят на остановках\
трамвая, ожидая луну.\
Медленный поцелуй — как рассвет, который\
мало помалу отнимает у ночи звёзды.\
Странствует влюбленное сердце бродяги и легки его поцелуи, так трамвай\
проходит танцуя, чтобы ночь разбудить.\
Ветер, как поцелуй внезапный, меняет небо.\
Извилистые поцелуи заползают под кожу.\
Его поцелуи задирают юбки, как апрельский ветер.\

\*\*\*

\
из-за поэзии носки у меня дырявые\
ногти грязные\
борода подстрижена плохо\
пепельница полная\
живот втянут\
я весь исцарапан\
и окно у меня открыто
