# Элио Пекора

> Элио Пекора (Elio Pecora) - итальянский поэт, писатель и эссеист. Родился в Сан Арсенио (Салерно) в 1936 г. Он автор стихов, романов, критических очерков, пьес, прозы и стихов для детей, редактировал антологии итальянской поэзии и публичные поэтические чтения, сотрудничал с газетами, еженедельниками, журналами и программами Rai. Руководит международным журналом «Поэты и поэзия».
>
> \(1936\)

<br/>

**Голоса**

Есть много голосов,\
что в наши дни звучат,\
так много и всё разных,\
все нужно слушать.\
Есть наши голоса,\
что говорят слова,\
одно тянет другое:\
не могут в одиночку жить.\
Есть голос ветра,\
что дует и освежает,\
есть воробья и кошки,\
и даже воды прозрачной,\
что меж камней скользит,\
есть деревьев шелест,\
шорох листьев,\
стрекотанье кузнечиков.\
Есть голос пламени -\
трещит, краснеет,\
есть голос моря - \
то загремит, то стихнет.\
A, если ночью в комнате\
прислушаешься,\
то услышишь медведя плюшевого,\
он смеется и кланяется\
на цыпочках.\
Есть тайный голос,\
что в себе мы носим,\
он всегда сопровождает нас,\
предупреждает нас и утешает.\
Их так много - голосов\
за нашей дверью,\
все нужно слушать.\
\
<br/>

**Песня**

Eщё я могу сказать, что любовь вечна,\
пока внутри есть огонь, она длится все время;\
и завтрашняя любовь стоит той,\
что мы называли любовью вчера .\
\
И это любовь - ехать в поезде,\
навстречу небу, окутанному тенями,\
навстречу ветру, дышащему в листьях,\
навстречу отблескам огней далекого праздника.\
И голос в телефоне - любовь,\
и внезапное воспоминание, которое исчезает,\
и жест, и клятва, которые yже недействительны,\
коль скоро все бежит, меняется, ускользает.\
\
Поэтому я повторяю - любовь вечна,\
ведь она нужна каждому,\
и желание найти эту любовь,\
сопровождающee нас каждый день, тоже вечно:\
oно зовет нас в надежде, что мы не сдадимся.
