# Винченцо Пизану

> Винченцо Пизану (Vincenzo Pisanu) родился 7 мая 1945 года в Урасе, в провинции Ористано, Сардиния. Всегда связанный с культурными событиями Сардинии, он предпринял первые инициативы по защите сардинской поэзии и языка, организуя литературные премии, сольные концерты и дебаты, радиопередачи. Eго стихи (как на сардинском так и на итальянском) неоднократно получали высочайшее одобрение жюри и самые представительные премии.\
> \
> (1945)

**Как дождь**

Это как дождь внезапный -\
вдруг окатит тебя\
неожиданно и,\
медленно просачиваясь, насквозь пропитает.\
Это как дождь, что капает\
капля за каплей, но с собою несёт\
дикие реки,\
полные гальки, отполированной\
буйным потоком.\
Камнем на душу ляжет\
молчание твоё в моем пенье,\
и вкус прощания, который мы оба уже ощущаем,\
и тоска по "люблю тебя", что уже стала болью.\
Она как дождь -\
эта любовь, что еще не созрела,\
нежная, отвергнутая, запретная -\
даже попробовать мы её не успели.\
Это желание бесконечного,\
скрытое в улетаютающих каплях,\
в будущем сбудется может году,\
а может не сбудется вовсе.\
Это дождь льёт, когда прозрачная, ты идёшь\
к своему устью, что растворяется в море.\
Это дождь слёз, что сдерживать надо\
не показав никому, как тебе больно.\
Дождь - это в воздухе пыль из любви,\
что въедается в поры и кожу\
из воды, которая есть ты сама,\
из этой жажды моей,\
которой мало всех звезд...\
Хочу тебя, хочу бесконечно.\
Три часа, но ещё я не сплю...\
Прости же за то\
что в тебя я влюбился.

**Подруга**

Не хватай\
вытянутой рукою\
последнюю белую розу\
с моей ветки,\
ты уколешься...\
Не ласкай\
розовым платьем\
мои пожелтевшие листья,\
вышивку\
порвать можешь.\
Не копай\
ради игры жестокой\
мою выжженную землю,\
ручей слез\
ты найдешь под нею,\
умоешься ими...\
Не срывай\
ради мимолетной секунды\
последней сладости завесу,\
ты оставишь мне\
только горечь\
стены из тени,\
последнюю черную\
жемчужину в шкатулке.\
Прогуляйся легко\
над моими бедными корнями\
и уйди ...\
Запах, что ты чувствуешь,\
не весенний,\
он исчезнет, когда задует ветер,\
первые дожди\
смешаются с пылью\
и земля станет\
просто грязью.

**Должен же прибыть поезд**

Должен же прибыть\
поезд\
откуда-нибудь.

Поезд, что мчится\
навстречу ветру,\
между дюн\
щёгольски извиваясь.\
Только я увижу его\
в этой гуще пьес,\
где мы все играем.

Расписанием для него будет солнце,\
путевым листом будет\
вечность,\
меж товарных и скорых\
он проследует\
в молчании,\
куда его душа направит.

Должно же быть\
место, где все\
пути скрестятся,\
куда по аркам мостов\
мы из снов въедем,\
где услышим вальс,\
что больше не играют,\
и где, может быть, снова

я смогу танцевать с тобою.

**Акварель (только ты)**

В этом обволакивающем дуновении ветра\
только ты одна\
невидимыми объятьями растапливаешь\
застывшие мысли. Дрожь листьев,\
и в танце быстром теней пастельных\
капли солнца падают на ворота,\
образуя узоры из светотени.\
Только тебя одну, и трещины на стенах,\
как нацарапанные строчки любовных писем.\
Между плющом и ступенькой мягко краснеет\
черепица, застенчиво пробивается клевер.\
Только ты одна, только тебя хочу в потоке\
этого холодного воздуха, что раскачивает\
меня между землей и небом,\
твою грудь, что толкает мою, как два хлеба,\
мягких и теплых, набухших и щедрых.\
В руках, в теле и в сердце, живьём тебя ощущаю.\
Только ты в этом дыхании ветра\
хрупком, как сама жизнь,\
мощным, как сила пальцев\
в отчаянии сжатых, переплетенных,\
чтоб удержать подступившие слезы,\
закат наступает\
момент за моментом.

Только ты\
в этом дыхании ветра,\
только ты.
