# Антонио Риккарди

> Антонио Риккарди (Antonio Riccardi) — итальянский поэт, писатель и литературный критик. Он собрал свои стихотворные произведения в томе «Доходная прибыль» (1996) и присутствует в антологии Франко Лои и Давиде Рондони «Il pensiero Dominati», изданной Гарзанти. Сотрудничал и сотрудничает с различными журналами и газетами. За свои работы он получил, среди прочего, премию Десси, премию Бранкати, премию Монделло и премию Леричи Пеа. С января 2017 года является редакционным директором издательства «СЭМ».
>
> (род. 1962)

Кто-то из семьи уехал в Бразилию\
ещё до войны, не от голода\
и не из принципов. Вернувшись в Парму\
oн ничего не помнил.\
Тридцать лет, а что рассказывать:\
несколько приключений,\
несколько сомнительных диковин.\
Просто из-за обширности тех мест\
это, наверняка, можно было предвидеть.

\*\*\*

Девочками они подолгу остаются в одиночестве,\
взрослыми женщинами становятся неотразимы.\
Такие они - сирены.\
По вечерам в некоторых широтах видно как они\
со своей мягкой очаровательной кожей под медь\
плавают в переливающихся волнах.\
Иногда и днем выходят они на сушу,\
обязательно оставаясь в тени, под портиками,\
и тогда чувствуют, как расцветает в них сожаление.
