# Франческо Томада

> Франческо Томада (Francesco Tomada) живет в Гориции, где преподает биологию и химию в средней школе. С середины девяностых годов он участвовал в национальных и международных чтениях и встречах, а также в радио- и телепередачах в Италии и за рубежом. Его тексты публиковались в многочисленных журналах, антологиях, плакатах и на сайтах в Италии, Словении, Канаде, Франции, Словакии, Литве, Австрии, Мексике, Испании, Швейцарии, Бельгии.
>
> (род. 1966)

**Грамматика**

Когда дети говорить начинают,\
целые фразы они не произносят,\
слова их смешны и несовершенны,\
но мячик есть мячик,\
а кошка - кошка,\
и выученная, она остается с тобой навечно.\
Mне из всего итальянского надо немного,\
всего несколько слов, но чтоб сказать\
уверенно\
мама, папа, сын мой,\
а ещё слово дом – как скобки, которые закрывают\
слово мы.

**Три делить на два**

Я помню, мы однажды шутили:\
если мы разойдемся, как наших трех детей э\
поделим, по полтора на каждого?\
пополам будем резать?\
глупая была шутка, еще глупее\
настоящее, в котором это, похоже, сбылось,\
и на самом деле - все дети теряются,\
а три делить на два дает ноль.
