# Франко Арминио

> Франко Арминио (Franco Arminio) - поэт, режиссер и писатель. Он сотрудничает с различными газетами, включая Corriere della Sera, снимает документальные фильмы и активно участвует в гражданских битвах, таких как борьба против закрытия больницы Бисачча и создания свалок в Альта-Ирпинии. Он написал множество книг, получил несколько наград (Стивен Дедал, Примо Леви и Вольпони), а также снял несколько фильмов. Он определяет себя как пезолог (paesologo), представитель-создатель взгляда на человека как на жертву процесса, в котором церковь, капитализм и загрязнение окружающей среды разделяют ответственность за то, чтобы заставить нас поверить в то, что мы всегда должны бежать, чтобы чего-то достичь, тогда как вместо этого все, что нам нужно, оно уже здесь, под рукой.

\*\*\*

я и потом буду тебя искать.\
может и не существует жизнь после смерти,\
но, протестуя, атомы свои я рассую повсюду:\
внутрь дерева, под черепицу, в туфли.\
\
\*\*\*\
\
у некоторых женщин запах есть\
под горлом -\
запах существования,\
тогда есть и форма у сосков,\
и рёбер свет,\
и голос, и желанье, что рвёт запястья\
и наполняет вены красными тельцами.\
у некоторых женщин есть сладость жестов,\
абсолютно сводящая с ума.\
\
\*\*\*\
\
одна женщина существует\
не знаю зачем,\
другая женщина, должно быть,\
затем же, что и муравьи,\
затем же, что и облака,\
но должна же быть женщина,\
которая и воздух, и бог,\
и плоть открытая.\
\
\
\
\*\*\*

Bозьми меня с собой в супермаркет,\
возьми меня в бар, возьми меня\
на парковку госпиталя.\
Разорви своим поцелуем нить,\
на которой повис я.\
Возьми меня на просёлочную дорогу,\
где лают собаки,\
рядом с механической мастерской,\
возьми в парфюмерную лавку.\
Возьми меня туда где мир,\
не туда, где поэзия.\
\
\*\*\*\
\
**Боль мне нужна**

\
Боль мне нужна,\
я не чувствую без неё ничего,\
не люблю без неё ничего.\
Дайте мне самую сильную боль,\
дайте любовь.\
\
\*\*\*\
\
**В истории любви**

\
В истории любви\
важно, кто любит, а не кого любят.\
В истории любви\
хотя бы один из двух,\
околдованный,\
скорее всего заблуждается.\
