# Марио Бенедетти

> Марио Бенедетти (Mario Benedetti) родился и вырос в Удине, переехал в Падую в 1976 году, где окончил факультет литературы и защитил диссертацию. Посвятил себя преподаванию литературы в высшей школе, сначала в Падуе, а затем в Милане, городе, куда он переехал. Его жизнь, его поэзия и образ жизни характеризовались наличием хронической болезни: особой формы рассеянного склероза, которая сопровождала его с детства. Все стихи Бенедетти собраны в одной книге Tutte le poesie (Garzanti, 2017) .\
> \
> (1955-2020)

**Этого так мало**

Того что ты знаешь,\
того что ты знаешь обо мне,\
так мало,\
того что ты знаешь\
о моих облаках,\
о моём молчании,\
о моих жестах,\
так мало того, что ты знаешь\
об этой печали при виде\
моего дома снаружи,\
о жалюзях моей печали,\
о колокольчике моей печали.\
\
Впрочем, ты не знаешь\
ничего по-настоящему,\
иногда ты думаешь,\
как мало того, что я знаю\
о тебе,\
как мало того что я знаю,\
о твоих облаках,\
о твоём молчании,\
о твоих жестах\
как мало того, что я знаю\
об этой печали при виде\
твоего дома снаружи,\
о жалюзях твоей печали,\
о колокольчике твоей печали.\
\
И ты мне не звонишь.\
И я тебе не звоню.

**Сирена**

Я убеждён, что ты не существуешь\
и всё же я слышу тебя каждую ночь.\
\
Порой тебя я выдумываю, может быть, от тщеславия\
или от лени, а, может быть, просто в отчаянии,\
\
от бесконечности моря идёт моё восхищенье,\
словно псалмами заслушиваюсь я твоим пеньем,\
\
и до того убежден я в твоём несуществовании,\
что жду тебя даже во сне, который увижу лишь завтра.\
\
