# Чезаре Вивиани

> Чезаре Вивиани (Cesare Viviani) родился в 1947 году в Сиене, в 1971 году окончил юридический факультет, защитив диссертацию по теме «плагиат» (тотальное психическое подчинение) в области судебной медицины. В 1972 году он переехал в Милан, где работал журналистом, а затем психологом в учреждениях здравоохранения. В 1973 году он зарекомендовал себя как поэт благодаря своей дебютной книге L'ostrabismo cara, опубликованной в издательстве Feltrinelli. В течение многих лет он сотрудничал с обзорами и выступлениями на психологические и социальные темы для газет «Il Giorno», «Corriere della Sera» и «Avvenire». Является лауреатом нескольких литературныж премий.
>
> (род. 1947)

**Они были правы, сказав нам: не ходите дальше**

Они были правы, сказав нам: не ходите дальше,\
доберитесь до большого виноградника и вернитесь.\
Посмотрите на то, что вы уже знаете,\
липы на аллее,\
ряд ив вдоль канавы,\
сад у старого источника, рощу.\
Затем появятся дома Сан-Ромоло,\
а вы так и идите до часовни и рядов.\
Идите обычным путем, пусть это\
будет просто прогулка.\

**Кто никуда не стремится остается в могиле, как есть**

Кто никуда не стремится\
остается в могиле, как есть,\
как его опустили.\
Кто вместо этого хочет добиться\
чего-то лучшего - занят,\
он ищет дыру, чтоб попасть\
в тьму самую темную,\
в тишину абсолютную,\
в вечность постоянную.
