# Коррадо Говони {style="gray"}

> Коррадо Говони (Corrado Govoni), впервые опубликовал свои стихи еще до первой мировой войны. Его считают отцом литературного движения «Kрепускуларизм», буквально означающего «Сумерки» и занимающегося скромными предметами, меланхолией и самоанализом. О себе он писал «Я всегда любил грустн ые вещи, бродячую музыку, песни о любви, которые поют старики в тавернах, молитвы монахинь, пестрых оборванных и больных нищих, инвалидов, грустную осень, полную прощаний... все грусти любви, грусти работы, грусти пустяков».
>
> (1884-1965)

<br/>

**То, что делает воскресенье воскресеньем**

Тёплый запах хлеба, пекущегося в духовке.\
Петушиная песня из курятника.\
Пенье канареек, доносящееяся из окон.\
Скрип вóрота и стук ведра о стенки колодца.\
Бельё, разбросанное на траве.\
Солнечные блики на подоконниках.\
Свежая скатерть на столе.\
Зеркала в комнатах.\
Цветы в стаканах.\
Бродяга, заставляющий плакать свою гармошку.\
Крики трубочиста.\
Милостыня нищим.\
Снег.\
Замёрзший канал.\
Звон колоколов.\
Женщины в чёрном.\
Новости.\
Чёрно-белые звуки пианино.\
Монахини, замотанные в белое,\
будто они ранены.\
Священники в чёрном.\
Больные в сером.\
Синева ясного неба.\
Прогулки влюблённых.\
Прогулки больных.\
Шум деревьев.\
Белые кошки за стеклом.\
Верчение красных флюгеров.\
Хлопание дверей и окон.\
Золотая кожура апельсинов на мостовой.\
По переулкам дети, играющие в серсо.\
Бьющие в садах фонтаны.\
Воздушные змеи, парящие над домами.\
Солдаты в синем, выполняющие манёвр.\
Лошади, стучащие копытами о мостовую.\
Девушки, продающие фиалки.\
Павлин, распускающий хвост над красной лестницей.\
Голуби воркующие на крыше.\
Миндаль, цветущий на монастырском дворе.\
Розовые олеандры в прихожих.\
Белые шторы, трепыхающиеся на ветру.

<br/>

**Кораблекрушение**

На моей потерпевшей кораблекрушение голове,\
ухватившись за сломанный стол,\
как за материнскую колыбель,\
плыву по черному морю жизни.\
Я вижу, как качаются звезды, словно\
нежные ветки миндального дерева.\
Свет из внешнего мира\
или головокружение от\
чарующих бездн небытия?

<br/>

**Сладость**

Синие воскресенья весны.\
Снег на домах, как белый парик.\
Прогулки влюбленных по каналу.\
Хлеб, выпекаемый воскресеным утром.\
Мартовский дождь, стучащий по серым плиткам.\
На стене расцветающая глициния.\
Белые занавески на окнах монастыря.\
Субботние колокола.\
Свечи зажжённые перед мощами.\
Зеркала с подсветкой в ​​комнатах.\
Красные цветы на белой скатерти.\
Золотые лампы, которые загораются вечером.\
Кровавые сумерки, умирающие на стенах.\
Распустившиеся розы на постели больного.\
Игра на фортепиано в день праздника.\
Песня кукушки в селе.\
Кошки на подоконниках.\
Белые голуби на крышах.\
Мальвы в горшках.\
Нищие, которые едят на порогах церквей.\
Больные на солнце.\
Маленькие девочки в дверях, расчесывающие волосы на солнце.\
Женщины, поющие у окна.
