# Алессандро Д’Агостини

> "Camerino di Prova" (Примерочная), удивительное произведение поэтического проекта Д'Агостини, из которого читатель “узнает”, что произойдет при переходе в загробную жизнь.
>
> (род. 1972)

**Примерочная**

Был бы это просто водораздел,\
а не кончина,\
пересечь бы его одним шагом\
и жизнь бы продолжалась,\
иным манером,\
в иных формах.

Была бы это просто дверь «раздевалки»\
в которую быстро входят,\
чтобы сбросить всё со старого тела\
и в новое переодеться,\
и в нём ходить на том свете.

Тогда одна забота у нас была бы:\
надеяться, что портной хороший,\
что для души он быстро сошьёт\
костюм по последней моде,\
чтобы носить в том месте неизвестном,\
где мы устроим новую жизнь,\
в ней больше не будет плоти.

На примерке удовлетворённые\
в зеркало мы бы смотрелись:\
элегантные, лёгкие такие,\
перед прыжком\
мы обернулись бы на секунду,\
чтоб взглянуть сочувственно, но без ностальгии,\
на тяжёлый груз старых костюмов,\
их рукавов и брючин,\
на воздух густой, где они остаются\
безжизненные — как в заключенье.
