# Франческа Дженти

> Франческа Дженти (Francesca Genti), pодившаяся в Турине, но проживающая в Милане, опубликовала сборники стихов «Бимба Урбана» (2001, Модена) и «Настоящая любовь не имеет лесных орехов» (2004, Меридиано Зеро, Падуя), “La ballata di Nina Simone“, 2022 (Баллада о Нине Симоне) и др. Ниже переводы двух ее стихотворений, опубликованных в сборнике “Poesie d'amore per ragazze kamikaze”, 2009 (Стихи о любви для девушек-камикадзе).
>
> (род. 1975)

Надеюсь, что я умру весною\
Под солнцем, что сверкает до боли,\
Я надеюсь быть сильной и молодою,\
и умереть с размахом вот такою\
в дикой аварии на Kавасаки[^дженти-1].

[^дженти-1]: \*Кавасаки – марка мотоцикла.

Я надеюсь, что в день аварии\
ты мне скажешь горькую правду,\
и не останется у тебя времени передо мной\
извиниться, и всю жизнь ты будешь жалеть\
об этом.

Я надеюсь, что в небесной лазури\
что-то звериное для тебя будет,\
и синева для тебя станет невыносимой,\
с нею на похороны будет идти совсем худо:\
небесный синий должен быть цветом,\
в котором нет ничего от цвета,\
чтоб чёрный в сравнении с ним казался\
отразившимся в металле и крови солнцем.\

\*\*\*\

Было так красиво не целовать тебя\
на заброшенной скамейке,\
на заднем плане в перспективе - аллея.

с тобой я скрываюсь от всего мира.\
мы изобрели день совершенно абсурдный:\
меланхоличный имплозивный музыкальный\
загадочный бесконечный безмерный.

чувствую боль в солнечном сплетении,\
чувствую голову полной, но опустевшей.\
точно как в третьем классе,\
когда я в первый раз влюбилась.
