# Гвидо Каталано

Гвидо Каталано (Guido Catalano) родился и всегда жил в Турине, городе, к которому сильно привязан. Писать он начал еще в школьные годы. Он посещал классическую среднюю школу, в 17 лет он был фронтменом сумасшедшей рок-группы Pikkia Froid, для которой писал тексты. Когда группа распалась, он начал читать тексты песен и обнаружил, что они «напоминают стихи». После окончания средней школы он поступил в университет на факультет современной литературы. Прежде чем стать профессиональным поэтом, он брал на себя самую разную работу: корректор в издательстве Эйнауди, швейцар в доме, художник-зарисовщик. В 2000 году опубликовал свой первый сборник “I canni hanno sempre ragioni” («Собаки всегда правы»); в 2005 году он открыл свой блог, который разбогател вместе с социальными сетями, чтениями и поэтическими слэмами. В 2016 году он опубликовал свой первый роман «D’amore si mori ma io no» (Ты умираешь от любви, а я нет) , частично автобиографический. Ниже представлены мои переводы его стихов из сборника “Piuttosto che morire m’ammazo, Mondadori, 2024 (“Скорее я убью себя, чем умру”).

\
**Ты знала всё**

Я помню,\
что твоя любимая пицца — с ветчиной и грибами, но без грибов.\
«Почему бы тебе не съесть её просто с ветчиной?» я спрашивал тебя каждый раз.\
«Почему ты не занимаешься своими делами?» ты отвечала мне\
и улыбалась.\
\
Я помню,\
что мы встретились весной,\
ты любила стрелять в голубей из своей забавной пневматической винтовки.\
«Попробуй!» ты сказала мне,\
А я сказал: «нет, для меня это слишком».\
\
Я влюбился в тебя\
еще и потому, что\
в разговоре ты могла вставлять маленькие подсознательные фразы\
в середину любого предложения,\
типа:\
«Этим летом я хотела бы пойти на курсы стрельбы из лука, моя подруга начала их посещать, ты красивый,\
и она говорит, что ей очень весело»\
или:\
«Вчера отвезла машину к электрику, ты устроил мне чертовский секс,\
он взял с меня сто пятьдесят евро за два отсоединенных проводкa»\
\
а может быть это была\
твоя безусловная любовь к пластилину,\
мы могли играть с ним часами\
в тишине\
голые, прямо\
на паркете твоего дома\
\
«Я хотела бы жить с тобой в пластилиновом доме» — ты сказала мне.\
«И слепить малышей из пластилина?» спросил я тебя,\
«да, — ответила ты, — и готовить вкусные блюда из пластилина»\
\
ты никогда не повышала голос,\
ты очень хорошо умела ненавидеть глазами,\
у тебя была очень белая кожа в веснушках,\
мы и встретились весной.\
\
«Пока ты меня любишь, ты никогда не напишешь обо мне», — сказала ты.\
«А вот и напишу», - сказал я.\
«Вот увидишь» сказала ты\
и улыбнулась,\
\
и, как всегда, была права,\
ты знала всё.**\
**

### **Три смерти**

**человек, который умер от изумления**

человек, который умер от изумления,\
незадолго до смерти от изумления\
находился в комнате с двумя дверями,\
одной открытой,\
а другой закрытой,\
открытая была та, через которую он вошел,\
закрытая же была та, которая открылась позже,\
и когда он открыл её, он увидел то, что сразило его намертво.\
\
это была ошеломляющая вещь,\
настолько ошеломляющая, что мужчина был так сильно поражен\
невероятным изумлением, что, как указано в заголовке \
(мы полагаем - возможно, ошибочно),\
от изумления умер.\
\
но по какой такой причине мы не можем сказать,\
что было такого изумляющего, что привело человека к катастрофе,\
и даже если бы мы это раскрыли, объяснение потерялось бы из-за\
атмосферы загадочности, несомненно присутствующей\
в этом кратком описании.\
\
вот единственная подсказка, которую, по совести говоря, мы хотим дать - просто в комнате не было:\
ничего голого\
ничего мертвого\
ничего мягкого\
ничего синего.

**\
человек, умерший из-за кретина**

не как кретин,\
в том смысле, что у него не было идиотской смерти,\
но по какой-то неясной причине\
все, абсолютно все,\
постоянно называли его кретином\
\
он встал утром,\
«кретин» сказала ему жена,\
он почистил зубы,\
«кретин», сказала ему дочурка,\
он пошел в бар,\
«кретин», - обратился к нему бармен,\
подавая ему капучино,\
пришёл на работу и все, от вахтёра до офис-менеджера,\
обзывали его "кретином",\
как будто шёл кретинский дождь,\
ей богу.\
\
человек, умерший из-за кретина,\
умер из-за кретина одним зимним вечером,\
последнего "кретина" выдал ему\
двадцатисемилетний служащий заправочной станции,\
человек, умерший из-за кретина,\
рухнул на руль\
и умер\
от разрыва сердца,\
мы этому верим?\
да, верим.

\
**человек, умерший от сицилийской кассаты**[^каталано-1]**\
\
**из трех смертей, составляющих этот смертельный триптих,\
эта самая простая и объяснимая.\
\
человек, умерший от сицилийской кассаты,\
умер после того, как съел девять кило сицилийской кассаты\
менее чем за два часа,\
мы не знаем, почему он это сделал,\
но мы знаем, благодаря надежному свидетелю,\
что его последними словами были:\
«в любом случае, что бы вы ни думали, я наконец полностью оценил её вкус».

[^каталано-1]: *сицилийская кассата – действительно очень вкусный традиционный сицилийский пасхальный сладкий пирог с риккотой, фруктами, марципанами, фисташками и шоколадом*

*\
***SBR**[^каталано-2]

[^каталано-2]: "SBR" - сокрашение означяюшее "вкус поцелуя девушки" (Sapore di Bacio di Ragazzа).

что мне нравится,**\
**так это вкус поцелуя молодой девушки,\
почти всегда вкус поцелуя молодой девушки -\
это одна из самых прекрасных вещей,\
вкус поцелуя молодой девушки\
сделан из тумана и цветка,\
я не знаю, какого цветка,\
может быть, этого цветка и вовсе не существует,\
он, поцелуй, влажный, мягкий и сладкий,\
он - дикий,\
да,\
есть что-то дикое, туманное и сладкое\
во вкусе поцелуя молодой девушки,\
а еще есть аромат духов,\
и конфетный аромат,\
но не конфет, которые продаются в кондитерской,\
это аромат конфет, который ты можешь найти\
только на губах целующей девушки,\
тебе придется закрыть глаза,\
чтобы хорошо распознать\
вкус девичьего поцелуя,\
ты должен закрыть глаза\
и ты почувствуешь его,\
вкус девичьего поцелуя не похож на вкус ни мёда,\
ни сахара, ни молока,\
если что-нибудь из фруктов, то это\
фрукт, состоящий сразу из множества фруктов,\
фрукт,\
который тебе не найти на рынке\
\
виноград? - спрашивал бы тебя зеленщик,\
гранат? - спрашивал бы он тебя,\
яблоко?\
нет, фрукт на вкус, как поцелуй молодой девушки,\
но фрукт, который ты, зеленщик, не можешь найти,\
вкус девичьего поцелуя,\
он и потом остается на губах,\
даже спустя много минут,\
даже спустя много часов,\
дней, если тебе повезёт,\
вкус девичьего поцелуя,\
он тебе никогда не надоест,\
лучшего вкуса нет на свете

**Без названия**

дерево смотрит на меня и\
смеётся,\
река смотрит на меня и\
смеётся,\
небо смеётся, глядя на меня,\
а ещё гора\
и лошадь,\
они смеются,\
\
прислоняюсь к стене -\
она смеётся,\
вилка смеётся, когда я накручиваю на нее спагетти,\
и даже спагетти смеётся,\
\
я смотрю на солнце,\
солнце смеётся и облака смеются,\
птицы смеются,\
хлеб смеётся, когда я отламываю кусок,\
\
смеётся бездомная собака,\
смеётся собака на поводке,\
смеётся охотничья собака,\
кот смеётся, когда я глажу ему спину,\
\
я завязываю шнурок и тот смеётся,\
смеётся туфля,\
сигарета смеётся, когда я зажигаю её спичкой,\
и спичка тоже смеётся,\
мои очки смеются,\
мои зубы смеются, пока я их чищу,\
зеркало смеётся, когда я смотрю в него,\
твои глаза смеются,\
\
улица смотрит на меня,\
смеётся,\
светофор смотрит на меня,\
смеётся,\
смеётся по ночам, глядя на меня,\
тоска\
и стакан,\
он тоже смеётся,\
\
я не смеюсь.\

**Волшебное стихотворение, чтобы заставить тебя снова развеселиться**

Это стихотворение волшебное,\
оно не логичное стихотворение.\
Прочитай его, стоя только на одной ноге,\
правой,\
удерживая страничку левой рукой,\
надев синюю шляпу,\
можно и красную,\
однако желтого цвета избегай,\
но если у тебя есть только желтые шляпы,\
они тоже отлично подойдут\
\
Это волшебное стихотворение,\
его следует читать вслух\
очень громко, если можешь,\
кричи его,\
стоя на одной ноге,\
по возможности, с кошкой на плече.\
Если у тебя есть собака,\
скажи ей, чтобы притворилась кошкой.\
Она тебя любит и для тебя это сделает,\
поэтому тебе придется иметь  на голове шляпу,\
цвет по твоему выбору,\
кошку на плече\
или собаку, которая притворяется кошкой.\
Если твоя собака страдает ожирением,\
подожди, приспособь её к шее.\
\
Тебе понадобится свежее, не жареное, но сваренное не вкрутую, а всмятку, яйцо.\
Если тебе не нравится всмятку, то можно и вкрутую,\
имей в виду, что кошки не любят яичницу,\
собаки, которые притворяются кошками, тоже могут помочь,\
но если ты не выносишь даже мысли стоять на одной ноге\
с цветной шляпой на голове\
и котом на плече\
или с фальшивой кошко-собакой, свернувшейся калачиком у тебя на шее,\
без яичницы в правой руке,\
иди за жареной едой.\
\
Это волшебное стихотворение, которое снова сделает тебя счастливой,\
так что тебе должно быть удобно,\
пока ты очень громко его читаешь\
в центре комнаты.\
Важно, чтобы ты находилась в комнате,\
не на открытом воздухе,\
поскольку, если люди увидят тебя\
громко читающей это стихотворение\
посреди улицы\
с кошкой на плече\
или собакой, притворяющейся кошкой, свернувшейся у тебя на шее,\
с цветной шляпой на, возможно, зеленой голове,\
на одной ноге,\
с жареным яйцом в правой руке...\
н-да...\
Ты тоже пойми, девочка, сегодня проснувшаяся грустной,\
что твой день\
может иметь не очень веселое развитие,\
типа: сначала принудительное лечение,\
потом я должен  приехать и забрать тебя из сумасшедшего дома,\
не говоря уже о собаке в питомнике\
и кошке под машиной,\
и это совсем\
не то,\
чего\
нам хотелось бы\
\
Нам хотелось бы, чтобы ты улыбалась\
прямо сейчас,\
это стихотворение волшебное,\
вот для чего оно нужно\
\
и знаешь, оно ведь\
может это сделать.\
\
**Иду, иду**

Ночью мне не уснуть, я смотрю, как ты спишь,\
и думаю, какой я везучий, ведь дано же мне,\
чтобы ты лежала в постели, такая белая,\
голая, пахнущая фруктами, хлебом и мылом,\
с черными волосами, которые, если я придвигаюсь,\
щекочут мне нос, а волосы твои тоже\
так замечательно пахнут.\
И пока спишь, ты говоришь во сне,\
но я не понимаю, что тебе снится, потому что\
шепчешь ты на языке лесных эльфов.\
Я смотрю на тебя, свернувшуюся калачиком в постели.\
Мне кажется, ты видишь хороший сон,\
если он станет хуже, я разбужу тебя поцелуями,\
не волнуйся, я караулю тебя и спать не хочу,\
мне так нравится смотреть на тебя между этими\
красными простынями, контрастирующими\
с твоим белым обнаженным телом ночью в постели.\
А вот и свет,\
свет начинающегося дня,\
свет и птицы,\
птицы, что воспевают день приходящий,\
и прощаются с уходящей ночью.\
Ранним утром день входит в нашу постель,\
освещая нас своим светом,\
ослепляя меня\
белизной твоей кожи.\
Во сне ты переворачиваешься.\
Краями губ я легко касаюсь кончика твоего носа\
и тихо тихо встаю,\
тихо тихо иду,\
иду, прихожу на кухню\
и варю нам\
кофе.

\
**14 минут**

когда солнце погаснет\
внезапно\
нам понадобится 8 минут, чтобы это заметить\
\
это напоминает мне о том, как ты\
тогда посмотрела мне в лицо\
и сказала «знай, я тебя больше не люблю»\
\
мне потребовалось 14 минут, чтобы это понять\
прошло 13 минут 59 секунд\
прежде чем наступила темнота\
и холод\
\
значит к этому моменту\
ты была уже дальше, чем солнце\
\
непонятно, как мне выжить\
непонятно, как тебя снова\
разжечь\
\
следовало бы спросить Маргариту Хак[^каталано-3]\
но у нее, скорее всего, есть дела поважнее.\

[^каталано-3]: Маргаритa Хак - Знаменитaя итальянскaя астрофизик.

**диалог между женщиной и мужчиной недостижимой печали с безнадежным финалом\
\
**– когда ты перестал?\
- перестал что?\
- любить меня\
– я никогда не любил тебя\
– когда ты это заметил?\
- заметил что?\
– что ты никогда не любил меня\
- в первый же раз, когда мы спали вместе\
– ночью?\
- нет, когда ты проснулась\
– это очень печально\
- да, правда\
– ты можешь представить себе что-нибудь более печальное?\
- честно говоря, могу, но признаю, что и это очень печально,\
и Рождество,\
и то что я допил Маaлокс[^каталано-4]\
– извини, я не поняла\
- ничего, я разговаривал сам с собой\
– а что теперь?\
- ну, я бы сказал, теперь каждый сам за себя, а Бог за всех\
– это всегда так заканчивается?\
- не знаю, хочешь амаретто?\
– я ведь не буду тебя ждать\
- я знаю\
- ты плачешь?\
– нет, аллергический конъюнктивит\
– как ты можешь быть таким бесчувственным?\
– просто в детстве я упал в бочку, полную волшебного супа бесчувствия\
- ты всегда заставляешь меня смеяться\
- я рад\
– тогда до свидания?\
- тогда пока

[^каталано-4]: Mаaлокс – средство от изжоги.

**Любовный контракт\
**\
Как и договорились я разлюбил тебя и\
согласно контракту начиная с сегодняшнего дня\
я больше не буду мечтать о тебе\
я больше не буду думать о тебе вздыхая под луной\
а луна, в свою очередь перестанет смеяться надо мной.\
Я не буду мучить бедные беззащитные ромашки\
срывая их мягкие белые лепестки\
я не буду просто гулять по городу\
боясь и надеясь случайно встретить тебя\
возвращаясь к местам наших первых поцелуев.\
Согласно нашему договору\
я буду добр и спокоен\
я улыбнусь, когда кто-нибудь расскажет мне о тебе\
и не буду покушаться на жизнь отъявленных ублюдков\
которые уже начали за тобой ухаживать.\
Согласно договоренности\
я обязуюсь, подчиняясь действующим правилам\
перестать писать тебе стихи о любви\
или хотя бы уменьшить\
их поток, становящийся опасным.\
Кроме того я перестану желать\
твое тело, мягкое и ароматное.\
Наконец, я клянусь, что буду твоим другом\
мудрым и верным, как говорится\
вроде собаки\
ты увидишь, что у меня это получится.\
\
Я только прошу тебя\
не верь ни одному слову\
из того, что ты только что прочитала.\
\
**Светлая\
** *\
*Она любила спать допоздна\
ей нравились стихи о любви\
особенно поэтов девятнадцатого века\
умерших молодыми, возможно\
из-за болезни легких\
а еще хрустящая еда\
кладбища\
устрицы\
короткие платья\
моя борода\
мой живот\
изготовление сигарет вручную\
а когда я спросил её:\
хочешь быть моей маленькой рыжеволосой девочкой?\
она ответила:\
сначала мне нужно покраситься в рыжий цвет, а потом\
тебе нужно стать более застенчивым со мной.\
А что, я не кажусь тебе достаточно застенчивым?\
спросил я,\
совсем не кажешься,\
но ведь у меня круглая голова, сказал я,\
правда, признала она, но тебе не хватает бешенной собаки.\
Мы много болтали\
особенно в ночное время.\
Она терпеть не могла сахара в кофе и\
отсутствия доброты в людях\
она всегда хотела играть в настольный футбол\
хотя играла очень плохо и сердилась на меня.\
Она говорила, что я ей нравлюсь, потому что я забавный парень.\
Я притворялся злым, но был счастлив.\
Она любила спать допоздна\
ей нравились стихи о любви\
особенно, когда в стихах говорилось о ней.\
\
\
