# Джорджио Капрони

> Джорджио Капрони (Giorgio Caproni), по роду деятельности школьный учитель, был автором огромного количества замечательных стихов, из которых лишь очень немногие были переведены на русский язык.
>
> Один из его главных критиков, Карло Бо, писал о Капрони так: “Поэт солнца, света и моря”. Свои стихи Капрони, в основном, посвящал городам, в которых родился и вырос, Ливорно и Генуе, а также матери и жене Рине.
>
> (1912-1990)

<br/>

**Листья**

Сколько ушло их...\
Много.\
А что же осталось?\
Даже ни вздоха.\
Даже следов от царапин\
или укусов.\
Все\
бесследно\
исчезли, от себя ничего\
не оставив.\
Как\
не остается следов\
на мраморе от подувшего ветра.\
Как\
не остается следов от тени\
на тротуаре.\
Всё\
исчезает в пыли,\
застилающей зренье.\
Там,\
за стеклом,\
голосов приглушённых шёпот,\
будто листья дышат неслышно.\
Листья, о которых\
ведaeт только сердце,\
ум в них не верит.

<br/>

**Записка, оставленная перед тем, как я не уехал**

Если я не вернусь,\
знайте, что я никогда\
и не уезжал.\
Всё моё путешествие -\
это пребывание\
здесь, где меня и не было никогда.

<br/>

**Рине**

Если мир принимает и цвет, и жизнь,\
то этим я обязан тебе, любимая…

<br/>

**Возвращение**

Я вернулся туда,\
где никогда не был.\
С тех пор, как меня тут не было,\
ничего не изменилось.\
На столе, покрытом\
клетчатой клеенкой,\
нашел стакан, который\
никогда не наполнял.\
Всё здесь осталось тeм же,\
словно никогда это и не покидал.\

**Жизнерадостность**

\
Было холодно.\
Ветер резал пальцы.\
Дыхание перехватывало.\
А я никогда еще не был так счастлив.

<br/>

**Перестаньте мучиться**

Xотите со мной встретиться,\
ищите меня там, где нет меня.\
Другого места подсказать не могу.

<br/>

**Откровение**

Я решился.\
Я обернулся.\
Я быстро, одному за другим,\
зaглянул в глазамоим убийцам.\
У каждого из них– у всех – было мое лицо.\
<br/>

**Встреча**

В свежем воздухе запах\
извёстки от новых домов,\
миг: и ничего не осталось во мне,\
– взмах ресниц,\
и паника удивления\
в твоем черном, свеpкающем взгляде\
словно лён полыхнул на мгновение,\
так быстро ты мимо прошла.\
<br/>

**Почти закончив подъём**

-Синьор, возвращайтесь в долину.\
То, что вы ищете перед собой,\
осталось у вас позади, за спиной.\
<br/>

**Каденция**

Тоника, терция, квинта,\
малая септима. Так и\
не разрешится\
жизни моей аккорд?\
<br/>

**Тьмa**

Даже фонаря с собой\
не возьму. Тьмa\
там такая тёмная,\
что eё просто нет.\
<br/>

**Рине II**

Без тебя дерево\
больше не будет деревом.\
Ничто без тебя уже\
не будет тем, что оно есть.\
<br/>

**Сердце**

Сердце бьется в центре\
Парижа. Бьётся\
на площади Согласия. Бьётся\
среди деревьев Елисейских Полей.\
Сердце бьется в сàмом сердце\
сàмого сердца Парижа.\
<br/>

\
**Геральдика**

Любимая, как больно\
ранен век, а мы так одиноки\
- ты и я - в той серости\
без имени. Время соловья и льва прошло.\
Герб сломан. Бесследно\
единорог оставил этот мир:\
Тень в сердце у меня.
