# Патриция Кавалли

> Итальянская поэтесса Патриция Кавалли (Patrizia Cavalli) родилась в Тоди, муниципалитете провинции Перуджа в центральной Италии, и жила в Риме. Она является автором многих сборников стихов, включая Con passi giapponesi (2019), My Poems Won’t Change the World: Selected Poems (2013), Datura (2013), Flighty Matters (2012), Pigre divinità e pigra sorte (2006), Sempre aperto teatro (1999) и L’io singolare proprio mio (1992) и лауреатом многих премий.
>
> (1947-2022)

\*\*\*

Не полагайся на мое воображение,\
не доверяйся ему, я не буду хранить тебя,\
не положу на полку и не оставлю на зиму,\
нет, я открою тебя сразу и съем в один присест.\
\

\*\*\*

Раньше, когда ты уходила, то забывала всегда\
то духи, то платок носовой, самый красивый,\
то новые брюки, то подарки друзьям,\
то сапоги, то перчатки и зонтик.\
В этот раз ты оставила\
пару трусов\
желтых пуэрториканских.\
\

\*\*\*

Maрроканцы со своими коврами –\
вылитые святые,\
а на самом деле – просто торговцы.\
\

\*\*\*

**Ну чтож, посмотрим, как ты цветёшь**

Ну чтож, посмотрим, как ты цветёшь,\
как раскрываешься,\
какого цвета лепестки твои\
и сколько пестиков,\
какие трюки знаешь, чтобы\
пыльцу свою разбрасывать\
и повторять себя, цветешь ты\
вяло или бурно, увидим, как ты подрезан,\
куда склоняешься, а коль умрёшь,\
засохнешь или скиснешь,\
ну, вперед, я на тебя смотрю,\
давай, цвети!\

**Жизнь так утомительна**

Жизнь так утомительна! Ведь знает,\
что должна закончиться, что\
приговорена, но даже умирая,\
утомляет. Даже урезанная,\
упрямо делает своё -\
жить продолжает.\

**Терапия**

О, дайте мне комнату в гостинице,\
комнатушку, комнатушку в гостинице,\
да, комнату, комнату в гостинице,\
комнатушку, комнатушку в гостинице...\
(...так всё и будет продолжаться\
не останавливаясь,\
пока уставшая и измученная\
ты не свалишься полумёртвая\
на любую койку,\
хоть не застеленную, хоть грязную.)\

\*\*\*

Как это грустно - щёлканье и скрип суставов!\
Всякий раз напоминают о скелете,\
пока прикрытом милосердной плотью.\

\*\*\*

Два часа назад я влюбилась.\
Дрожу от любви и продолжаю дрожать,\
и не знаю толком, кому я открыться должна.\

\*\*\*

Я стала очень мудрой,\
я говорю мудрости одну за другой,\
легко, очень легко.\
Я говорю их и тут же забываю,\
я могу забывать их,\
потому что у меня всегда про запас есть ещё одна.\
К тому же,\
я не из тех, кто экономит!\

\*\*\*

**Всё так просто**

Всё так просто,\
да, было так просто,\
так очевидно, что\
я почти в это не верю -\
тело предназначено вот для чего:\
чтобы касаться меня или не касаться,\
чтобы обнимать меня или отталкивать,\
а остальное оставим придуркам.
