# Франческо Карофильо

> Франческо Карофильо (Francesco Carofiglio) — итальянский архитектор, писатель, режиссёр и поэт. Сын писательницы Энцы Буоно и брат писателя и члена итальянского ceнатopа Джанрико Карофильо. О своем поэтическом сборнике ”Poesie del tempo stretto” (Стихи о трудных временах) он писал так “В детстве я играл с рисунками. Я делал это часами, каждый день. С годами это стало ежедневной необходимой привычкой. Затем появились слова, рассказы, романы. И тайно стихи. В этой книжечке рисунки и стихи впервые идут вместе, без видимой связи. И они становятся маленькими историями, мимоходом рассказанными в нескольких строках, в нескольких словах.”\
> \
> (род. 1964)

\
в моей памяти о том августовском дне\
у моей матери усталые глаза,\
удивляет на ее красивом лице\
подчеркнутая морщинами\
улыбка\
\
\*\*\*\
\
потом в конце коридора я вижу\
своего отца\
в легком плаще,\
он подходит и берёт меня за руку,\
мы переходим улицу\
на противоположный тротуар,\
он улыбается и уходит,\
а я остаюсь один,\
на всю жизнь\
\
\*\*\*\
\
кошка, размахивая хвостом,\
рисует круг\
и внезапно ей в голову приходит\
мысль о тигре\
