# Джузеппе Конте

> Джузеппе Конте живет в Сан-Ремо. Автор многочисленных сборников стихов, эссе и романов, посвященных природе, эросу и мифам. Ниже приведены переводы его стихов из сборника “L’Oceano e il Ragazzo”, 2002 (Океан и мальчик).**\
> **\
> (1945)

**Этрусские животные**

Они входят в смерть сухо улыбаясь,\
с собранными сзади и спущенными\
набок волосами, приготовившиеся\
уйти не вспоминая, руки падают\
у них как чужие; многие держат\
зеркало, от себя справа.\
они входят туда, где больше не умирают.\
Пройдя сквозь темную глубину выплывают\
наверх и мчатся по морю на летающих\
дельфинах, на драконах, на квадригах\
грифòнов.\
То что вы видите — рассыпаные\
вокруг чèрепа листья, кору, мусор -\
не было «человеком».\
Была безымянная радость, легкость\
камня, крыльев, солнца.\

Грифòн с клювом орла, с телом изящным,\
скорее собачьим чем конским,\
пожирает нежное мясо оленя,\
упавшего на спину, выгнутую дугою,\
ноги его словно палки торчат -\
упал, но не плачет.\
У молчащего дерева бег свой закончил\
олень, а каждое дерево лèсу начало\
дает, потому будут еще у оленя\
золотые акации, будут и утра.\
У грифòна пустые глаза и твердые крылья -\
бродяга, а как каменный нынче застыл -\
нет в нем ни ненависти, ни желаний,\
и почему, сам не знает,\
страсть убивать в нем неизбывна.

**Метаморфозы любви**

*Хотя они тонут в море, они воскреснут снова;\
хотя влюбленные пропадут, любовь не погибнет.\
(Дилан Томас, «И смерть не будет иметь власти»)*

Окрестили меня Джузеппе, но\
теперь у меня больше нет имени:\
я - ящерицы и пчелы, я - камни и мимозы,\
я - море: меня ты не сможешь больше узнать,\
больше не сможешь сказать мне: любимый.\
Мы сможем летать вместе с солнечными роями\
из чужих и соседских ульев, крошиться\
на скалистых пляжах среди крутых оползней,\
двумя раковинами лежать в тишине\
на дне морском.

**Акт обожания молодежи**

Ты верил, что уйдёшь, юноша,\
как гость неблагодарный,\
что не попрощавшись выходит из дома,\
как иней, исчезающий с горного луга,\
как проходящее утро.\
Вместо этого ты все еще рядом со мной.\
Ты верил, что ты умный, мучая меня и\
причиняя мне столько боли\
своей мутной неврастенией,\
своим неудовлетворенным желанием,\
своей девственной застенчивостью,\
всегда заставлявшей меня кривить рот.\
Но ты все еще здесь, несмотря на\
волосы, волосы, которые увядают,\
ногти, которые слоятся и выпадают,\
кости, которые сопротивляются,\
тебе хочется остаться со мной опять.\
Оливковая ветвь, стебель мака\
ты тайна, душа, сюрприз,\
ты блуждающая, обманчивая красота\
площадей неизвестного города, по которым я\
торопливо бесцельно бродил на рассвете.\
Ты думал, что уходишь, но я\
слишком хорошо принимаю тебя в своем сердце,\
свирепый мальчик, которого ничто не приручило,\
который слишком хорошо знает мою ласку\
и как феникс возрождается из моего пепла.\
Оставайся же здесь, чтобы я почитал тебя.\
\
**Однажды, если кто-то прочитает меня**

Однажды, если кто-то прочитает меня в\
третьем тысячелетии, то узнает, что и тогда были\
деревья и были желания, были пальмы и были сосны,\
были эвкалипты с листьями, как четвертинки луны,\
и были розы, были те, кто не хотел больше страдать, и те, кто\
хотел любить всё на свете, а еще были те, кто сами себе\
в подарок подносили стихи - далекие и жестокие,\
простые и слабые.
