# Вивиан Ламарк

> Вивиан Ламарк (Vivian Lamarque) известнa не только своими стихами, но и сказками для детей. Онa преподавалa итальянский язык иностранцам и литературу в частных лицеях, переводила на итальянский Лафонтена, Валери, Превера, Бодлера. С 1992 года пишет для газеты Вечерний Курьер. Луреат многочисленных премий за ее поэзию и прозу, в том числе очень престижной премии Стрега за ее последний сборник стихов L’amore da vecchia (Любовь Старухи) и премию Джанни Радари за ее сказки.
>
> (род. 1946)

**Кондоминиум**

Тихо спускаюсь, внизу\
на третьем этаже спит мёртвый\
сосед. Он вернулся сегодня вечером\
из больницы, его подняли по\
лестнице, ему открыли дверь\
без звонка, в последний раз\
он использовал глагол “входить”.\
Он спал с нами, другими жильцами,\
ночь казалась нам всем одинаковой,\
он спал восемь часов, но потом опять\
и опять, и опять после утренней побудки солдат,\
после того как солнце поднялось высоко в небе,\
теперь, когда мы двигаемся он больше не такой как мы.\
Этот жилец мёртв. Он без ног сойдет по лестнице.\
Он был добр, он стоял у окна, у него была канарейка,\
у него была своя доля в кондоминиуме,\
смотри, у него пробиваются крылья.\
\

**Кто знает, будет ли со мной мой любимый...**

Кто знает, будет ли со мной мой любимый,\
когда я окажусь на грани смерти,\
мне бы так хотелось, чтобы да,\
чтобы он был совсем рядом со мной,\
ведь это в последний раз,\
и чтобы он говорил мне какие-то трогательные вещи,\
например, мне так жалко, что ты умираешь.\
\

**Мой любимый, кто знает какие фартучки**

Мой любимый, кто знает, какие фартучки\
ты носил, когда был маленький,\
и был ли ты хорошим мальчиком или так себе,\
мой любимый, знать бы мне,\
когда ты был маленький, где ты,\
тебя бы украла.\
\

**Господин на дне моря**

Один господин иногда отправлялся на дно моря,\
чтобы увидеть множество проплывающих мимо разных рыб.\
А рыбы его замечали?\
Да, рыбы смотрели на господина даже после того,\
как он выходил из моря, и даже спустя много лет\
они его вспоминали.\
\

**Господин в сердце**\
Он вошел в ее сердце.\
Пройдя сквозь глаза и уши\
он вошел в её сердце.\
И что он там делал?\
Жил.\
Он жил в её сердце как дома.\
\

**Господин напротив**

Синьор сидел напротив синьоры, сидевшей напротив него.\
От них справа/слева было окно, от них слева/справа была дверь.\
Там не было зеркал, однако в этой комнате\
они полностью отражались друг в друге.\
\

**Господин точечка**

Не было у неё возможности всегда его видеть,\
и когда она наконец могла смотреть на него,\
то смотрела долго долго, до последней минуты,\
до самой последней секунды, и даже после того,\
как он отвернулся, как он отвернулся.\
Господин становился все меньше и меньше, он был\
уже почти нераспознаваем, но она его прекрасно узнавала,\
даже в виде крошечной точeчки там внизу.\
\

**Господин спокойной ночи**

Из далёкой постели с самыми лучшими побуждениями\
она желала ему спокойной ночи.\
Была ли луна?\
О да, и луна, и тысячи звёзд, и ветви деревьев, и\
спящие воды, все вместе они желалали ему спокойной ночи.\
A слышал ли их господин?\
Да, хоть еле-еле и уже засыпая, господин их всё-таки слышал.\
\

**Господин который ушел**

Он был господин, который ушёл.\
А ей здесь так его не хватало.\
Воздух вокруг неё\
был полон его следами.\
Вот так перевешанная картина\
стену помечает навечно.\
\

**Снежная дама**

Снег шёл и шёл, и дама очень любила господина.\
Снег ложился на город, а любовь дамы ложилась на господина.\
Днём и ночью шёл снег, a дама днём и ночью укрывала гоподина своей любовью.\
Наполовину занесённые город и господин,\
замученные нескончаемыми снегопадом и любовью,\
ждали весны.\
\

**Дама в спешке**

Навсегда сталo теперь очень коротким.\
Сколько осталось рождественских праздников?\
Гoрстка.\
Значит она не должна была терять ни минуты?\
Да, ей нужно было торопиться,\
и из-за этого она поспешно его любила.\
\

**По окончании отпуска**

Отпуск заканчивается, из поездa виднo,\
как люди на пляже продолжают играть и купаться,\
их отпуск еще не закончен:\
также ли будет, также ли будет при уходе из жизни?\
\

**Госпожа последнего раза**

Когда он видел ее в последний раз,\
он не знал, что видит ее в последний раз.\
А почему?\
Потому что таких вещей никогда не знаешь.\
И что же, он не был к ней добр в последний раз?\
Был, но на вечность этого не хватает.\
\

**Повелитель сна**

С каждым наступлением ночи она посылала ему мысли,\
так подходившие для часа молчания и поцелуев.\
И эти так подходившие мысли, переползая с крыши на крышу,\
добирались до него, почти охваченного сном,\
едва не опоздав, но все-таки вовремя.\
\

**Господин, который не приезжал**

Одна госпожа всегда поджидала у окна\
господина, который не приезжал.\
Почему же она его поджидала?\
Потому что она не знала, что господин не приедет,\
мы знали, а она нет.\
\

**Господин, у которого не было окна**

Господин, у которого не было окна, не мог знать какая погода на улице.\
Чтобы это узнать ему нужно было открыть дверь и выйти посмотреть.\
Или позвонить по телефону одной госпоже и та ему все рассказывала.\
Какая сегодня погода?\
Сегодня идет снег, говорила госпожа господину, у которого не было окна.\
Снежинки готовились упасть с неба тысячами, одна за другой.\
\

**Первая моя любовь**

Первая моя любовь, первая моя любовь\
их было две разом.\
Потому что у него был близнец – очень\
на него похожий, и того я любила тоже.\
Oдинаковые были первые мои любoви,\
но один был повеселее, а другой,\
рядом с братом, смотрел на меня серьёзней.\
Вечером у окна я всегда была с этим,\
но первая моя любовь, первая моя любовь\
их было две разом:\
он и его близнец – с ним рядом.\
\

**Для моего жениха**

Для моего жениха\
я свяжу шарф,\
длинный-предлинный,\
белый-пребелый.\
Я свяжу шарф\
такой как дорога,\
на этой дороге\
мы встретимся,\
на этой дороге\
мы поцелуемся.\
\

**Смотри: спящие животные**

Смотри:\
спящие животные,\
стали травой,\
луговой травой.\
А солнце заметило,\
что некоторых уже нет?\
А ты, луна умеешь считать?\
Ты замечаешь, что общее число\
вернувшихся сегодня вечером\
другое?\
\

**Птичьи Домики**

Птичьи домики не портят пейзаж.\
Они ничего не весят, у них цвет деревьев\
и в них никогда не теряешь из виду ни неба,\
ни земли, ни того, что меж ними.\
Вы входите в них без ключей, используя только крылья,\
вы отдыхаете в них, закрыв свои глазки,\
вы складываете крылья, которые ничего не весят,\
вы отдыхаете, чтобы завтра снова начать –\
летать.\
\

**Если на обратной стороне фотографий**

Если мы не напишем имена и фамилии\
на обратной стороне фотографий,\
то уже через два поколения,\
это все превратится в хор,\
бесконечный хор людей,\
склоняющихся над фотографиями,\
чтобы восклицать: и этот? а это та? а это\
ребенок? брат? кузен? но чей?\
Через широко открытые окна\
бесконечные эхо от вопрошающих\
восклицаний разнесутся в воздухе —\
и этот? а это, может быть, тот? а, может быть,\
дальний дядя? дальняя тётя?\
Но какой дядя и какая тётя?!\
Это была я, я, я!\
Я - фотография моя!\
\

**Это почти легко**

Сочинить стихотворение\
это почти легко,\
достаточно взять листок бумаги\
и карандаш,\
это также легко, как для земли сотворить\
травинку или ромашку.\
\

**Эти ракушки**

Этими ракушками, что я нашла,\
станем мы,\
мы приглаженные и успокоившиеся,\
уже без разноцветной боли,\
нами будут накрывать уши,\
чтобы слушать шум моря.\
\
