# Аттилио Лолини

> Aттилио Лолини (Attilio Lolini) - итальянский поэт и журналист. Лолина писал для «Унита», «Манифест» и «Куоре», а также для различных поэтических журналов, а также был музыкальным критиком и либреттистом. Его последняя книга стихов под названием «Обертка от сэндвича» вышла в свет в 2013 году.\
> \
> (1939-2017)

**Обертка от сэндвича**

Ветер за ставнями\
быстро меняет голос,\
то он зловещая песня,то вздыхающий воздух\
\
стòит окно приоткрыть, как\
падает со стен штукатурка и\
из переполненной пепельницы\
ветер высасывает окурки\
\
вещи и люди\
пытаются измениться\
принять иные формы\
прежде чем их забудут.\
\
\
**Лимоны**

Когда наступит утро\
не гляди по сторонам -\
эти странные дниразделяют слова\
и делают тусклым золото лимонов.\
Вставать не надо,\
лучше остаться в постелиили пойти погулять,\
не сделав ни шагу.\
\
**Ветки**

Кто бы мы ни были\
ветра достаточно,чтобы нас запутать\
Любезные слова,\
которым мы верим,\
они и летают любезно,\
Потом они падают на ветки\
и висят, чтобы смеяться\
сегодня и завтра.\
