# Микеле Мари

> Микеле Мари (Michele Mari) — итальянский романист, автор рассказов, академический критик и поэт. Автор трех поэтических сборников, в частности, Cento poesie d'amore a Ladyhawke, Einaudi, 2007 (Сто стихов о любви к Ледихоук); Мари преподает итальянскую литературу в Миланском государственном университете, он считается одним из ведущих экспертов по итальянской литературе XVIII века.
>
> (род. 1955)

**Ты не помнишь, но давным давно**

Ты не помнишь,\
но давным давно,\
так давно, что кажется, что это было не так,\
мы качались на одних качелях.\
\
Хоть бы это качание никогда не закончилось –\
строго говоря, это была\
моя единственная молитва,\
с которой за всю свою жизнь\
я когда-либо поднимался в небо.\

**Я всегда буду искать тебя**

Я всегда буду искать тебя,\
надеясь никогда не найти тебя,\
ты сказала мне при последнем прощании.\
\
Я никогда не буду искать тебя,\
всегда надеясь найти тебя,\
ответил я.\
\
В тот момент это блестящее остроумие\
казалось великолепным,\
но с каждым днём\
во мне созревает\
мысль, говорящая -\
два имбецила\
\

**В моей голове для тебя всегда была пустая комната**

В моей голове\
для тебя всегда была пустая комната,\
столько раз я приносил туда цветы,\
столько раз я защищал её от монстров.\
\
Теперь в этой комнатe живу я сам,\
a монстры зашли в неё вместе со мной.
