# Альдо Нове

> Альдо Нове (псевдоним Антонио Чентанин) итальянский писатель и поэт. В 1996 году, после окончания Миланского университета по философии морали, он написал “Вубиндa и другие рассказы без счастливого конца”, опубликованные Кастельвекки и переизданные Эйнауди в 1998 году под названием «Супервубинда». Эдоардо Сангинети включил его вместе с Тициано Скарпа и Джузеппе Каличети в свой Атлас итальянского двадцатого века, поместив их в конец «века авангарда» итальянской литературы. В 2022 году он опубликовал “Sonetti del giorno di quarzo” (Сонеты Дня Кварца) для Эйнауди.\
> \
> (род. 1967)

**Миф**

Когда я был маленький\
у нас во дворе был фонтан\
из которого била вода, она была во всем мире\
и мы с ней были очень похожи.\
Я разбрызгивал воду вокруг дома,\
и дом оставался твердым весь день\
и таким же всю ночь,\
в стране где был я,\
и моя семья.\
А иногда вода проливалась\
с небес и нас всех умывала\
она была\
сделана так же\
как та, из фонтана\
в нашем дворе,\
эта вода,\
она была в облаках\
а потом проливалась,\
в моей стране,\
на моем дворе новым\
дождем.
