# Джованни Рабони

> Джованни Рабони (Giovanni Raboni) - эрудит, эссеист, драматург, издатель, ангажированный критик, переводчик Пруста и Бодлера, ключевая фигура культурной жизни нескольких десятилетий и автор потрясающих стихов, сочетающих в себе черты модернизма и нео-реализма.\
> \
> (1932-2004)

**Страхи Магдалины**

У меня страх древесины и камней,\
у меня страх тела, страх порвать нерв,\
страх перерезать сухожилие, у меня страх света,\
у меня страх камня, который закроет твою дверь,\
у меня страх ветра и голосов, у меня страх\
вороны, которая тебя съест, у меня страх волка,\
я боюсь, что он найдет твои кости,\
что ты уже мертв и что каждую ночь\
я буду бояться твоего холодного поцелуя\
и что ты засунешь ноги мне под простыню.**\
\
\
**Cожаление вице-короля\*\*

Нет пути ни вперед, ни назад.\
Ты не смотришь ни налево, ни направо,\
ни ниже, ни выше. Теперь всё будет\
проводиться в соответствии с инструкциями,\
если бы только не эти дерьмовые апостолы -\
невероятные двенадцать человек,\
которые между смертью и жизнью\
всегда найдут какую-нибудь разницу.\
\
\
**Война**

Я ровесник своего отца – руки у меня почти его,\
особенно пальцы, ногти, изогнутые и немного\
утолщенные, лунообразные (но у меня\
без коричневых пятен от никотина)\
когда, помятый и безупречный, он путешествовал\
на военных поездах и автобусах,\
привозя к нам в разные сезоны из разных мест\
мирных отдыхающих,\
а в красивой легкой сумке\
странные продукты тех лет, плавленый сыр,\
варенье без сахара, бездрожжевой хлеб,\
образы темного города, разорванного города,\
я помню, такого милого нашим сердцам.\
Мы со страхом думали о его возрасте и\
с тех пор, как себя помню, время от времени,\
снизу вверх, я шептал молитву о его коронарных артериях.\
Долгое время с момента, как он ушёл в небытие,\
я день за днём становлюсь его братом,\
и вскоре стану старшим, мудрым братом.\
И мне бы хотелось знать,\
молятся ли, хоть иногда, за меня мои дети.\
Но тотчас же, противореча сам себе, говорю, нет,\
им не хватало другого, другой пищи, они хотели, чтобы\
между мной и ними не было никого, кроме меня,\
а то, что я им давал, разве это была пища для них?\
Как вор я уходил, пищи не было,\
и возвращался с пустыми руками...\
Бедная была эта война, простая и мерзкая,\
Я говорю себе, моя война была такая бедная,\
война упрямства и послушания. И пусть\
они это простят, и если к ним придёт\
желание помолиться, то пусть не за меня.
