# Умберто Фьори

> Умберто Фьори (Umberto Fiori) родился в Сарцане в 1949 году, с 1954 года живет в Милане, где получил высшее образование по философии. В 70-ых годах вошел в состав рок-группы Stormy Six в качестве голоса и гитариста (а позже и как автор). Покинув мир музыки в начале восьмидесятых, Фьори полностью посвятил себя поэзии. В 1986 году он опубликовал свой первый сборник стихов под названием «Дело» (Сан-Марко дей Джустиниани), за которым последовали, все изданные издательством «Маркос и Маркос», сборники «Примеры» (1992), «Кьярименти» (1995), «Парларе аль муро» (1996), Тутти (1998) и Прекрасная перспектива (2002). Преподаватель и эссеист, он работал профессором современной итальянской литературы в Миланском университете. В 2009 году вышел сборник стихов “Вы” (Мондадори). В 2014 году вышел том, в котором собраны все опубликованные тексты плюс неопубликованные: Poesie 1986-2014 (Mondadori).\

**Какие рты у вас, какие пальцы**

Какие рты у вас, какие пальцы.\
Сколько зубов.\
И как кусают. А как глотаете,\
как пьёте с закрытыми глазами,\
задумчивыми длинными глотками\
прямо из бутылки.\
Я? — нет, спасибо, пить я не хочу,\
и аппетита нет.\
\
**Тревога**

В разгар ночи по бульварам\
раскатывается сигнал тревоги.\
Затихают, и вновь раздаются\
две высокие ноты, громко, с пылом\
играющего ребенка.\
В темных стенах домов\
открываются окна, загораются лампы.\
Кроме дороги\
в гуще веток – пусто,\
ничего не видно.\
Раздвигаются занавески,\
и вокруг этого крика\
собираются люди, будто выстраиваются\
вокруг костра в поле.\
\
