# Джио Эван

> Джио Эван (Gio Evan) – многогранный художник, писатель и поэт, философ, юморист, исполнитель, автор песен и уличный художник. В период с 2007 по 2015 год он совершил велосипедное путешествие, в ходе которого объездил большую часть мира: Индию, Южную Америку, Европу. Он начал учиться и жить вместе с местными учителями и шаманами, а в Аргентине хопи крестил его как «Джио Эван». В 2019 опубликовал роман “Сто сердец внутри” (Cento cuori dentro). В 2020 опубликовал сборник стихов “Se c’è un posto bello sei te” (Если и есть красивое место, то это ты).
>
> (род. 1988)

**Нам сказали, что мы слишком много бегаем\
\
**нам сказали,\
что мы слишком много бегаем,\
что бегая,\
ты хорошо узнаёшь ветер,\
но остальное рискует размыться\
и потерять смысл,\
дерево может стать\
одним целым со скамейкой,\
скамейка одним целым с уличным фонарем,\
уличный фонарь с тротуаром\
и так все становится всем,\
из-за бега\
падение тоже становится сильнее\
и вставать после такой пробежки\
тяжелее.\
\
шрам никому не делает скидок,\
вы платите полную цену\
и он обосновывается тут,\
на поврежденной коже,\
навсегда\
\
они сказали нам, что мы слишком много бегаем,\
что нам придётся взять\
более спокойный темп,\
двигаться медленнее,\
держать дистанцию в один шаг,\
оценивать риск,\
выставлять руки вперед,\
словно возможно\
дозировать огонь во взгляде,\
словно любовь -\
это столовая с порционными блюдами\
\
они сказали нам,\
что мы слишком много бегаем,\
что бегая,\
мы хорошо узнаём ветер,\
но остальное рискует размыться\
и потерять смысл\
\
но они не знали\
что нам нравится вот так:\
бегать,\
чтоб на нашей стороне был ветер,\
а все остальное пусть размывается.\

**Дорогая, если тебе грустно\
\
**Дорогая,\
если тебе грустно,\
позвони мне\
хоть в полдень,\
хоть в полночь,\
помни,\
я предпочитаю бодрствовать с тобой,\
чем без тебя видеть тяжёлый сон,\
полный страшных предчувствий.\
\
Дорогая,\
если ты проиграешь,\
то позвони мне,\
чтобы я взял тебя отпраздновать что-нибудь:\
посмотреть сегодня на чистое небо,\
посмотреть на море, оно похоже на бассейн,\
посмотреть, как красиво эта мама обнимает сына,\
смотреть на тех двоих, что пьют кофе и целуются.\
Я напомню тебе, моя дорогая,\
что всегда есть что-нибудь,\
заслуживающее отпразднования.\
\
Моя дорогая, ты позвони мне,\
ведь мне не нужно много времени,\
чтобы объяснить тебе,\
что проиграть не значит потерпеть неудачу,\
один раз проиграешь,\
другой раз – выиграешь.\
\
Моя дорогая,\
если ты переживаешь дерьмовые времена,\
трудные времена,\
грустные дни,\
позвони мне хоть издалека,\
в любое время,\
и мы вместе выпьем вина.
